### ISSUE TITLE
Add aliases for -randommeme

### ISSUE THREAD

**Issue by soarn** [Memerator/Discord-Bot#1]
**Is your feature request related to a problem? Please describe.**
I feel that it takes far too long to get random memes, the command (`-randommeme`) is so long!
**Describe the solution you'd like**
Aliases!  Maybe `-rm` or `-rmeme` or `-meme`
**Describe alternatives you've considered**
The bot might also display the prefix in a status message?  Or respond when being mentioned.
**Additional context**
Have a wonderful day!

**Comment by Chew** [comment]
Thanks for the suggestion! We've added `-rm` `-rmeme` and `-random` as aliases for `-randommeme`. Hope this helps!
